import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#45464c",
        "on-tertiary-fixed-variant": "#444749",
        "border-hairline": "rgba(107, 114, 128, 0.1)",
        "on-surface": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#191c1e",
        "secondary-fixed": "#dce2f3",
        "surface-bright": "#f9f9f9",
        background: "#fbfbfb",
        "primary-fixed-dim": "#c0c6db",
        "on-primary-fixed": "#141b2b",
        error: "#ba1a1a",
        "surface-container-low": "#f3f3f3",
        "status-online": "#22c55e",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "border-card": "rgba(107, 114, 128, 0.12)",
        "on-primary-fixed-variant": "#404758",
        "brand-whatsapp": "#25D366",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed-dim": "#c5c6c8",
        "surface-container-high": "#e8e8e8",
        "surface-hover": "#e5e7eb",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff",
        secondary: "#585f6c",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#5e6572",
        tertiary: "#000000",
        "primary-container": "#141b2b",
        "inverse-primary": "#c0c6db",
        "outline-variant": "#c6c6cd",
        outline: "#76777d",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dce2f7",
        "secondary-container": "#dce2f3",
        primary: "#000000",
        "on-error": "#ffffff",
        "surface-dim": "#dadada",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-tint": "#575e70",
        surface: "#ffffff",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed": "#151c27",
        "brand-instagram": "#E1306C",
        "on-tertiary-fixed": "#191c1e",
        "brand-linkedin": "#0077b5",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e1e2e4",
        "on-secondary-fixed-variant": "#404754",
        "on-tertiary-container": "#828486",
      },
      letterSpacing: {
        "ultra-wide": "0.28em",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        margin: "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        loader: ["\"Plus Jakarta Sans\"", "Poppins", "sans-serif"],
        "title-base": ["Poppins"],
        "headline-lg": ["Poppins"],
        "display-2xl": ["Poppins"],
        "label-caps": ["Poppins"],
        "display-xl": ["Poppins"],
        "body-base": ["Poppins"],
        "headline-lg-mobile": ["Poppins"],
        "code-mono": ["Geist"],
        "body-sm": ["Poppins"],
        "headline-md": ["Poppins"],
        "label-micro": ["Poppins"],
      },
      fontSize: {
        "title-base": ["18px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "900" }],
        "display-2xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "900" }],
        "label-caps": ["14px", { lineHeight: "1", letterSpacing: "0.2em", fontWeight: "700" }],
        "display-xl": ["48px", { lineHeight: "1.15", letterSpacing: "-0.05em", fontWeight: "900" }],
        "body-base": ["16px", { lineHeight: "1.625", letterSpacing: "0", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "900" }],
        "code-mono": ["12px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.25", letterSpacing: "-0.025em", fontWeight: "900" }],
        "label-micro": ["10px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
